### ISSUE TITLE
Bad implementation of api 

### ISSUE THREAD

**Issue by dimovski-dev** [DDNet-Team-Searcher/website#2]
Every time you need to create a new API, you use the createApi({}) method, which is wrong.  Instead, you should create a base API, and inject the other APIs into it, thus "populating" it.

base.api.ts: 

```
export const baseApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  endpoints: () => ({}),
});
```

users.api.ts: 

`export const usersAPI = baseApi.injectEndpoints({...your endpoints})`

**Comment by dimovski-dev** [comment]
instead of baseUrl: '/' you can use your backend url. 

'/' can be used if u have more than 1 api

**Comment by MilkeeyCat** [comment]
For example i have baseApi and i call it in `users.api.ts`. What to do if all my endpoints in `users.api.ts` have prefix `users` in url, do i have to add `users` to every endpoint?

**Comment by dimovski-dev** [comment]
@MilkeeyCat 

probably this solution will be good for u: 

```
export const baseApi = (basePath) => createApi({
  reducerPath: basePath,
  baseQuery: fetchBaseQuery({ baseUrl: baseUrl }),
  endpoints: (builder) => ({})
});
```

```
export const usersApi = baseApi('users').injectEndpoints({
  endpoints: (builder) => ({...})
});
```

**Comment by MilkeeyCat** [comment]
> ```
> export const baseApi = (basePath) => createApi({
>   reducerPath: basePath,
>   baseQuery: fetchBaseQuery({ baseUrl: baseUrl }),
>   endpoints: (builder) => ({})
> });
> ```

doesnt it create a new api each time u call `baseApi`?
