### ISSUE TITLE
Prisma can't find database url

### ISSUE THREAD

**Issue by lukitsche** [DDNet-Team-Searcher/website#63]
I,ve clined gour repository and run docker compise up. Also I started the dev db script before.
I don't know how to use the .example.env file. I copied it to the projects root /.env. And also into the same folder.
I put the environment directly into the docker compiseyml file. Them it kind find the localhost:5432/ddts db. Even though I see the running container inside docker-deaktip dashboard.
I'm running debian 12.
I have no docker knowledge.
I want to make your project run locally on mz machine to start get an overview of it and maybe start contributing to it.

My ddnet bame is cauldron.
Where put the .env file?
Why can't prisma find the db even when iI put the url
In docker compose with the correct port uns url, and it's running in the dashboatd.

Sorry for typos I'm on phone github app.

**Comment by MilkeeyCat** [comment]
Hey! You should copy the `.env` file in the same directory where `.example.env` is. To run the website locally all you have to do is run the script in `scripts/start_db_dev.sh` and type `pnpm run dev` in root directory of the project.

**Comment by MilkeeyCat** [comment]
If these steps don't work, could you please send a screenshot of the error you get

**Comment by lukitsche** [comment]
![Screenshot from 2024-06-26 23-20-54](https://github.com/DDNet-Team-Searcher/website/assets/135062556/2cce45c9-7875-481e-98ee-b31ecf62508f)
I made it work, but it can't find the protos. The submodule is in packages/server/protos but it looks for packages/server/src/protos. Do I have to run some command inside packages/server/?

**Comment by MilkeeyCat** [comment]
I think I forgot to mention in the repo but you also need a protocol buffer compiler. You can install it on debian with ```sudo apt install protobuf-compiler```

**Comment by lukitsche** [comment]
No you mentioned it.

**Comment by MilkeeyCat** [comment]
Oh, you also have to run `pnpm run proto:generate` in `packages/server`

чт, 27 черв. 2024, 11:44 дп користувач lukitsche ***@***.***>
пише:

**Comment by lukitsche** [comment]
Okay works now. Thanks

**Comment by MilkeeyCat** [comment]
If it works, you can close the issue?
